# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-10 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vintage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre_form', models.CharField(default=0, max_length=10)),
                ('ano_mes_form', models.CharField(default=0, max_length=10)),
                ('ano_form', models.CharField(max_length=10)),
                ('campana', models.CharField(max_length=20)),
                ('flg_uso', models.IntegerField(default=0)),
                ('producto', models.CharField(max_length=25)),
                ('mora3_30d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora6_60d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora12', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ctas_uso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cuenta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('segmento_riesgo', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('flg_convenio', models.IntegerField(default=0)),
                ('linea_paralela', models.IntegerField(default=0)),
                ('canal', models.IntegerField(default=0)),
                ('flg_cierre', models.IntegerField(default=0)),
                ('uso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('uso_3m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('uso_6m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('uso_12m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('linea_tdc', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('ctas_linea_paralela', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora6_30d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
